//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> total_money { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
